/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'anacl' at '05/07/16 00:08' with Gradle 2.14
 *
 * @author anacl, @date 05/07/16 00:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
